# Generated by Django 5.2.14 on 2026-08-13 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0107_add_label_prompt"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="auto_annotation_function",
            field=models.CharField(blank=True, default="", max_length=256),
        ),
        migrations.AddField(
            model_name="project",
            name="auto_annotation_threshold",
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="auto_annotation_function",
            field=models.CharField(blank=True, default="", max_length=256),
        ),
        migrations.AddField(
            model_name="task",
            name="auto_annotation_threshold",
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
